language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '9'
install:
  - npm install -g codecov
  - yarn
script:
  - yarn compile
  - yarn test
after_success:
  - yarn coverage