language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
node_js:
  - '6'
install:
  - npm install -g codecov
  - yarn
script:
  - yarn lint
  - yarn compile
  - yarn test
  - codecov
after_success:
  - yarn coverage